[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Global function configuration
  directory = "netlify/functions"

# Scheduled function to run auto-check every 5 minutes
[functions."scheduled-check"]
  schedule = "*/5 * * * *" # every 5 minutes
  timeout = 900  # 15 minutes maximum

# Auto-check function configuration
[functions."auto-check"]
  timeout = 60   # 60 seconds (enough for 30 dates + buffer)

# Get cached result function
[functions."get-cached-result"]
  timeout = 30   # 30 seconds (fast response)

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000" 