[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Scheduled function to run auto-check every 30 minutes
[[functions]]
  path = "netlify/functions/scheduled-check.ts"
  schedule = "0 */5 * * * *"  # Every 30 minutes

# Background function configuration
[[functions]]
  path = "netlify/functions/auto-check-background.ts"
  timeout = 900  # 15 minutes maximum

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000" 