[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "false"

# Required environment variables (set these in Netlify dashboard)
# The build will fail if these are not set
[context.production.environment]
  # Supabase credentials (REQUIRED)
  SUPABASE_URL = "REQUIRED - Set in Netlify dashboard"
  NEXT_PUBLIC_SUPABASE_URL = "REQUIRED - Set in Netlify dashboard" 
  SUPABASE_SERVICE_ROLE_KEY = "REQUIRED - Set in Netlify dashboard"
  SUPABASE_ANON_KEY = "REQUIRED - Set in Netlify dashboard"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "REQUIRED - Set in Netlify dashboard"
  
  # Email configuration (REQUIRED)
  EMAIL_SENDER = "REQUIRED - Set in Netlify dashboard"
  EMAIL_APP_PASSWORD = "REQUIRED - Set in Netlify dashboard"
  
  # App configuration (REQUIRED)
  NEXT_PUBLIC_BASE_URL = "REQUIRED - Set in Netlify dashboard"
  USER_ID = "REQUIRED - Set in Netlify dashboard"
  CODE_AUTH = "REQUIRED - Set in Netlify dashboard"
  
  # Security tokens (auto-generated if not set)
  CRON_SECRET = "d47a7f5b61be83cb1d5de7f3c38fbf3ef6b5d2d1407f9874b159a0c36f76025d"
  ADMIN_SECRET = "f1039cc377c4a66a8167e943defe23a7e687d13b8cf11a2be91761dc39500234"

# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000"
# CRON_SECRET = "your-secret-key"
# ADMIN_SECRET = "your-admin-secret"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 