[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  CRON_SECRET = "d47a7f5b61be83cb1d5de7f3c38fbf3ef6b5d2d1407f9874b159a0c36f76025d"
  ADMIN_SECRET = "f1039cc377c4a66a8167e943defe23a7e687d13b8cf11a2be91761dc39500234"
  NEXT_USE_NETLIFY_EDGE = "false"


# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Global function configuration  
  directory = "netlify/functions"

# Auto-check function configuration
[functions."auto-check"]
  schedule = "*/5 * * * *" # every 5 minutes
  timeout = 900  # 15 minutes maximum (unlimited until we get it working)

# Email queue processing function configuration
[functions."process-email-queue"]
  schedule = "0 */2 * * *" # every 2 hours
  timeout = 300  # 5 minutes maximum

# Data cleanup function configuration
[functions."data-cleanup"]
  schedule = "0 3 * * *" # daily at 3 AM
  timeout = 300  # 5 minutes maximum

# Batch notifications processing function configuration
[functions."process-batch-notifications"]
  schedule = "*/30 * * * *" # every 30 minutes
  timeout = 300  # 5 minutes maximum

# Schedule auto-check function to run every 5 minutes
[[functions]]
  path = "/api/auto-check"
  name = "auto-check"
  schedule = "*/5 * * * *"

# Schedule process-cached-notifications to run 1 minute after auto-check
[[functions]]
  path = "/api/process-cached-notifications"
  name = "process-cached-notifications"
  schedule = "1-59/5 * * * *"

# Schedule process-email-queue to run every 2 minutes
[[functions]]
  path = "/api/process-email-queue"
  name = "process-email-queue"
  schedule = "*/2 * * * *"

# Schedule data-cleanup to run daily at 3 AM Israel time (1 AM UTC)
[[functions]]
  path = "/api/data-cleanup"
  name = "data-cleanup"
  schedule = "0 1 * * *"

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000"
# CRON_SECRET = "your-secret-key"
# ADMIN_SECRET = "your-admin-secret"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 