[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000" 