[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for automatic handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Global function configuration  
  directory = "netlify/functions"

# Auto-check function configuration
[functions."auto-check"]
  schedule = "*/5 * * * *" # every 5 minutes
  timeout = 900  # 15 minutes maximum (unlimited until we get it working)

# Environment variables needed for deployment
# Set these in Netlify dashboard:
# USER_ID = "4481"
# CODE_AUTH = "Sa1W2GjL"
# REQUEST_DELAY_MS = "1000" 